name: release

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: The target OS
        default: ubuntu-22.04
        required: false
      resource-group:
        type: string
        description: The azure resource group
        required: true
      app-name:
        type: string
        description: The app name
        required: true
      dotnet-version:
        type: string
        description: The dotnet version to use [3.0.x, 6.0.x], defaults to 6.0.x
        default: "6.0.x"
        required: false
    secrets:
      AZURE_CREDENTIALS:
        required: true
      NUGET_SOURCE_URL:
        required: true
      NUGET_AUTH_TOKEN:
        required: true

jobs:
  released:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      - name: Get publish profile
        id: publishprofile
        uses: joybusinessacademy/.github/.github/workflows/azure-publish-profile.yml@main
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: ${{ inputs.resource-group }}
          appName: ${{ inputs.app-name }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: ${{ secrets.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

      - name: Build
