name: Azure Function App (Build, Test & Deploy)

on:
  push:
    branches:
      - $default-branch
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - $default-branch
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: joybusinessacademy/.github/.github/workflows/dotnet-build.yml@main
    with:
      project-path: <project-path>
    secrets: inherit

  test:
    name: Test
    uses: joybusinessacademy/.github/.github/workflows/dotnet-test.yml@main
    secrets: inherit

  deploy_develop:
    name: Deploy Develop Environment
    if: github.ref_name == 'develop' && (github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: [build, test]
    strategy:
      fail-fast: true
      matrix:
        resource-group: [rg-online-regional-ent-dev-ae, rg-online-regional-ent-dev-eus]
    uses: joybusinessacademy/.github/.github/workflows/dotnet-deploy.yml@main
    with:
      environment: Development
      resource-group: ${{ matrix.resource-group }}
      app-name: <app-name>
      project-path: <project-path>
    secrets: inherit

  deploy_test:
    name: Deploy Test Environment
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: [build, test]
    strategy:
      fail-fast: true
      matrix:
        resource-group: [rg-online-regional-ent-test-ae, rg-online-regional-ent-test-eus]
    uses: joybusinessacademy/.github/.github/workflows/dotnet-deploy.yml@main
    with:
      environment: Test
      resource-group: ${{ matrix.resource-group }}
      app-name: <app-name>
      project-path: <project-path>
    secrets: inherit

  deploy_prod:
    name: Deploy Production Environment
    if: github.ref_name == 'master' && (github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: [build, test]
    strategy:
      fail-fast: true
      matrix:
        resource-group: [rg-online-regional-ent-prod-ae, rg-online-regional-ent-prod-as, rg-online-regional-ent-prod-eus, rg-online-regional-ent-prod-wus]
    uses: joybusinessacademy/.github/.github/workflows/dotnet-deploy.yml@main
    with:
      environment: Production
      resource-group: ${{ matrix.resource-group }}
      app-name: <app-name>
      project-path: <project-path>
    secrets: inherit