name: Create Sentry Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: The version e.g. `v1.2.3`
        required: true
      environment:
        type: string
        description: The environment e.g. `prod`
        required: false
        default: prod
      sentry-org:
        type: string
        description: The Sentry organization slug
        required: true
      sentry-project:
        type: string
        description: The Sentry project slug
        required: true
      sourcemaps:
        type: string
        description: Sourcemaps directory if any. (Optional)
        required: false
    secrets:
      token:
        required: true
        description: GitHub token with access to the repository
      sentry-auth-token:
        required: true
        description: Sentry API token

jobs:
  sentry:
    name: Create Release Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.token }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry-auth-token }}
          SENTRY_ORG: ${{ inputs.sentry-org }}
          SENTRY_PROJECT: ${{ inputs.sentry-project }}
        with:
          environment: ${{ inputs.environment }}
          sourcemaps: ${{ inputs.sourcemaps }}
          version: ${{ inputs.sentry-project}}-${{ inputs.version }}
