name: Deploy

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: The target OS, defaults to ubuntu-22.04
        default: ubuntu-22.04
        required: false
      environment:
        type: string
        description: The Github environment to use
        required: true
      resource-group:
        type: string
        description: The resource group
        required: true
      app-name:
        type: string
        description: The app name
        required: true
      project-path:
        type: string
        description: The path to the project to build
        required: true
      dotnet-version:
        type: string
        description: The dotnet version to use ['3.1.x', '6.0.x'], defaults to 6.0.x
        default: 6.0.x
        required: false
    secrets:
      AZURE_CREDENTIALS:
        required: true
      NUGET_SOURCE_URL:
        required: true
      NUGET_AUTH_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs-on }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.app-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: output
          path: output

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: ${{ secrets.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

      - name: Get publish profile
        id: publishprofile
        if: github.ref_name == 'master' || github.ref_name == 'develop'
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: ${{ inputs.resource-group }}
          appName: ${{ inputs.app-name }}

      - name: Deploy
        if: steps.publishprofile.outputs.profile != 0
        uses: azure/functions-action@v1
        id: deploy
        with:
          app-name: ${{ inputs.app-name }}
          package: output
          publish-profile: ${{ steps.publishprofile.outputs.profile }}
          slot-name: ${{ inputs.slot-name }}

      - name: Reset publish profile
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: ${{ inputs.resource-group }}
          appName: ${{ inputs.app-name }}
          reset: true
